package commands

import (
	"fmt"

	"github.com/spf13/cobra"
)

var (
	ciFormat     string
	ciAuthMethod string
	ciStage      string
)

var ciInitCmd = &cobra.Command{
	Use:   "ci-init",
	Short: "Generate CI pipeline snippet for vaultspectre",
	Long: `Prints a ready-to-paste CI job configuration to stdout.

Supports GitLab CI and GitHub Actions formats.

Examples:
  vaultspectre ci-init --format gitlab
  vaultspectre ci-init --format github --auth-method approle`,
	RunE: runCIInit,
}

func init() {
	ciInitCmd.Flags().StringVar(&ciFormat, "format", "gitlab", "CI format: gitlab, github")
	ciInitCmd.Flags().StringVar(&ciAuthMethod, "auth-method", "token", "Auth method: token, approle, kubernetes")
	ciInitCmd.Flags().StringVar(&ciStage, "stage", "validate", "CI stage name")
}

func runCIInit(_ *cobra.Command, _ []string) error {
	switch ciFormat {
	case "gitlab":
		printGitLabCI()
	case "github":
		printGitHubActions()
	default:
		return newExitError(ExitBadArgs, "unsupported CI format: %s (use gitlab or github)", ciFormat)
	}
	return nil
}

func printGitLabCI() {
	authFlags := authFlagsForCI()

	fmt.Printf(`# Generated by vaultspectre ci-init
# Paste into .gitlab-ci.yml

vaultspectre:scan:
  stage: %s
  image: ghcr.io/ppiankov/vaultspectre:latest
  variables:
    VAULT_ADDR: "${VAULT_ADDR}"
%s  script:
    - vaultspectre scan
        %s--repo .
        --fail-on-missing
        --format sarif
        > gl-secret-scanning.json
  artifacts:
    reports:
      secret_detection: gl-secret-scanning.json
    when: always
    expire_in: 7 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  allow_failure: false
`, ciStage, gitlabVarsForAuth(), authFlags)
}

func printGitHubActions() {
	authFlags := authFlagsForCI()

	fmt.Printf(`# Generated by vaultspectre ci-init
# Paste into .github/workflows/vaultspectre.yml

name: VaultSpectre Scan
on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install vaultspectre
        run: |
          curl -sSL https://github.com/ppiankov/vaultspectre/releases/latest/download/vaultspectre_linux_amd64.tar.gz | tar xz
          sudo mv vaultspectre /usr/local/bin/

      - name: Run vaultspectre scan
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
%s        run: |
          vaultspectre scan \
            %s--repo . \
            --fail-on-missing \
            --format sarif \
            > results.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
`, githubEnvForAuth(), authFlags)
}

func authFlagsForCI() string {
	switch ciAuthMethod {
	case "approle":
		return `--auth-method approle \
        --role-id "$VAULT_ROLE_ID" \
        --secret-id "$VAULT_SECRET_ID" \
        `
	case "kubernetes":
		return `--auth-method kubernetes \
        --k8s-role vaultspectre \
        `
	default:
		return `--token "$VAULT_TOKEN" \
        `
	}
}

func gitlabVarsForAuth() string {
	switch ciAuthMethod {
	case "approle":
		return `    # VAULT_ROLE_ID and VAULT_SECRET_ID must be set as masked CI/CD variables
`
	case "kubernetes":
		return `    # Uses Kubernetes ServiceAccount — no extra variables needed
`
	default:
		return `    # VAULT_TOKEN must be set as a masked CI/CD variable
`
	}
}

func githubEnvForAuth() string {
	switch ciAuthMethod {
	case "approle":
		return `          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
`
	case "kubernetes":
		return ""
	default:
		return `          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
`
	}
}
