package commands

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var (
	forceInit  bool
	withPolicy bool
)

const configTemplate = `# vaultspectre configuration
# Generated by: vaultspectre init
# Docs: https://github.com/ppiankov/vaultspectre

# Vault server address (or set VAULT_ADDR env var)
vault_addr: ""

# Vault namespace for Enterprise (or set VAULT_NAMESPACE env var)
# vault_namespace: ""

# Output format: text, json, sarif, spectrehub
format: text

# Days threshold for stale secret detection (0 to disable)
stale_days: 90

# Timeout in seconds for Vault API calls
timeout: 30

# Auto-detect variables from Ansible inventory files
detect_vars: false

# Exit with error if missing secrets found
fail_on_missing: false

# File patterns to exclude from scanning (glob syntax)
exclude_patterns:
  - "vendor/**"
  - "node_modules/**"
  - "*_test.go"
  - "testdata/**"
  - "**/*.example"

# Slack webhook URL for watch mode notifications (optional)
# slack_webhook_url: "https://hooks.slack.com/services/T.../B.../..."
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a starter .vaultspectre.yaml config file",
	Long: `Creates a .vaultspectre.yaml configuration file in the current directory
with sensible defaults and documented options.

Use --force to overwrite an existing config file.`,
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVar(&forceInit, "force", false, "Overwrite existing config file")
	initCmd.Flags().BoolVar(&withPolicy, "with-policy", false, "Also generate a policy.yaml file")
}

func runInit(_ *cobra.Command, _ []string) error {
	const configFile = ".vaultspectre.yaml"

	if !forceInit {
		if _, err := os.Stat(configFile); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", configFile)
		}
	}

	if err := os.WriteFile(configFile, []byte(configTemplate), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", configFile, err)
	}

	fmt.Fprintf(os.Stderr, "Created %s\n\n", configFile)
	fmt.Fprintln(os.Stderr, "Next steps:")
	fmt.Fprintln(os.Stderr, "  1. Set vault_addr in the config (or export VAULT_ADDR)")
	fmt.Fprintln(os.Stderr, "  2. Export VAULT_TOKEN (or use --token flag)")
	fmt.Fprintln(os.Stderr, "  3. Run: vaultspectre scan .")
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "Optional:")
	fmt.Fprintln(os.Stderr, "  - Add exclude_patterns for vendor/test directories")
	fmt.Fprintln(os.Stderr, "  - Set detect_vars: true for Ansible repos")
	fmt.Fprintln(os.Stderr, "  - Set fail_on_missing: true for CI pipelines")
	fmt.Fprintln(os.Stderr, "  - Use --with-policy to generate a policy.yaml")

	if withPolicy {
		if err := writePolicyTemplate(); err != nil {
			return err
		}
	}

	return nil
}

const policyTemplate = `# vaultspectre policy file
# Use with: vaultspectre scan --policy policy.yaml

# Maximum allowed findings by status (0 = none allowed)
max_findings:
  missing: 0
  error: 0

# All discovered paths must start with one of these prefixes
required_path_prefixes:
  - "kv/projects/"
  - "kv/shared/"

# Paths matching these prefixes are violations
forbidden_path_prefixes:
  - "kv/deprecated/"
  - "kv/test/"

# Maximum percentage of stale secrets (0-100)
max_stale_percent: 10
`

func writePolicyTemplate() error {
	const policyFile = "policy.yaml"

	if !forceInit {
		if _, err := os.Stat(policyFile); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", policyFile)
		}
	}

	if err := os.WriteFile(policyFile, []byte(policyTemplate), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", policyFile, err)
	}

	fmt.Fprintf(os.Stderr, "\nCreated %s\n", policyFile)
	fmt.Fprintln(os.Stderr, "  Edit the policy rules, then run: vaultspectre scan --policy policy.yaml .")
	return nil
}
